import openai
from flask import Flask, render_template, request

# Set OpenAI API key
openai.api_key = "<Enter API key>"	##	<---------------	API Key

app = Flask(__name__)

# Routes

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/results", methods=["POST"])
def results():
    user_input = request.form["user_input"]
    prompt = "The following is a response generated by the OpenAI GPT-3 language model.\nQ: " + user_input + "\nA:"

    try:
        response = openai.Completion.create(
            engine="davinci",
            prompt=prompt,
            max_tokens=1024,
            n=1,
            stop=None,
            temperature=0.5,
        )
        response_text = response.choices[0].text.strip()
    except Exception as e:
        print("Error:", e)
        response_text = "Sorry, there was an error generating a response. Please try again later."

    return render_template("results.html", user_input=user_input, response=response_text)

if __name__ == "__main__":
    app.run(debug=True)
